apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    openyurt.io/topologyKeys: {{ .Values.features.topologyKeys }}
  labels: 
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
spec: 
  clusterIP: 10.96.0.10
  clusterIPs: 
  - 10.96.0.10
  internalTrafficPolicy: Cluster
  ipFamilies: 
  - IPv4
  ipFamilyPolicy: SingleStack
  ports: 
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
  - name: metrics
    port: 9153
  selector: 
    k8s-app: kube-dns