{{- if .Values.config.auth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.auth.secret }}
  labels:
    {{- include "netbird-client.labels" . | nindent 4 }}
type: Opaque
data:
  {{.Values.config.auth.secretKey}}: {{ .Values.config.auth.value | b64enc | quote }}
{{- end }}