apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-servant-applier
  labels:
    app.kubernetes.io/name: node-servant-applier
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-servant-applier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-servant-applier
    spec:
      serviceAccount: node-servant-applier
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      {{- if .Values.parameters.workingMode }}
        - name: WORKING_MODE
          value: {{ .Values.parameters.workingMode }}
      {{- end }}
      {{- if .Values.parameters.nodeServantImage }}
        - name: NODE_SERVANT_IMAGE
          value: {{ .Values.parameters.nodeServantImage }}
      {{- end }}
      {{- if .Values.parameters.yurthubImage }}
        - name: YURTHUB_IMAGE
          value: {{ .Values.parameters.yurthubImage }}
      {{- end }}
      {{- if .Values.parameters.enableDummyIf }}
        - name: ENABLE_DUMMY_IF
          value: {{ .Values.parameters.enableDummyIf | quote }}
      {{- end }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: node-servant-applier
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      



