apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-servant-applier
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-servant-applier
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - get
  - create
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-servant-applier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-servant-applier
subjects:
- kind: ServiceAccount
  name: node-servant-applier
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-servant-applier
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-servant-applier
subjects:
- kind: ServiceAccount
  name: node-servant-applier
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: node-servant-applier
  apiGroup: rbac.authorization.k8s.io
