# Default values for yurthub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

cacheAgents: ""

yurthubBindingAddr: 127.0.0.1
kuberneteServerAddr:
  manual:
    enabled: false
    host: 127.0.0.1
    port: 6443
  lookup:
    enabled: true
    secretRef:
      name: hetzner
      namespace: kube-system
      keys:
        host: apiserver-host
        port: apiserver-port

bootstrapFile: "/var/lib/yurthub/bootstrap-hub.conf"
organizations: ""

image:
  registry: ghcr.io/openyurtio/openyurt
  repository: yurthub
  tag: v1.4.1
