apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "flannel.name" . }}-ds
  namespace: {{ .Release.Namespace }}
  labels:
    tier: node
    app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        {{- .Values.flannel.affinity | toYaml | nindent 8 }}
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: {{ include "flannel.name" . }}

      {{- if or .Values.flannel.installCNIPlugin .Values.flannel.installCNIConfig }}
      initContainers:
      {{- if .Values.flannel.installCNIPlugin }}
      - name: install-cni-plugin
        image: {{ .Values.flannel.image_cni.repository }}:{{ .Values.flannel.image_cni.tag }}
        command:
        - cp
        args:
        - -f
        - /flannel
        - /opt/cni/bin/flannel
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      {{- end }}
      {{- if .Values.flannel.installCNIConfig }}
      - name: install-cni-config
        image: {{ .Values.flannel.image.repository }}:{{ .Values.flannel.image.tag }}
        command:
        - cp
        args:
        - -f
        - /etc/kube-flannel/cni-conf.json
        - /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      {{- end }}
      {{- end }}
      containers:
      - name: kube-flannel
        image: {{ .Values.flannel.image.repository }}:{{ .Values.flannel.image.tag }}
        {{- if .Values.flannel.command }}
        command: 
        {{- range .Values.flannel.command }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.flannel.args }}
        args: 
        {{- range .Values.flannel.args }}
        - {{ . }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENT_QUEUE_DEPTH
          value: "5000"
        volumeMounts:
        - name: run
          mountPath: /run/flannel
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
        - name: xtables-lock
          mountPath: /run/xtables.lock
      volumes:
      - name: run
        hostPath:
          path: /run/flannel
      - name: cni-plugin
        hostPath:
          path: /opt/cni/bin
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: flannel-cfg
        configMap:
          name: {{ include "flannel.name" . }}-cfg
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
