{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.name" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
{{- end }}