image:
  repository: registry.k8s.io/coredns/coredns
  tag: v1.8.4

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - key: edgefarm.io
    effect: NoSchedule
