# based on: https://github.com/helm/charts-repo-actions-demo/blob/main/.github/workflows/lint-test.yaml
name: lint

on:
  push:
    branches:
      - main
    paths:
      - "helm/charts/**"
      - "!helm/charts/index.yaml"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "helm/charts/**"
      - "!helm/charts/index.yaml"
      - ".github/workflows/test.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "1.23"
          - "1.22"
          - "1.21"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (lint)
        run: |-
          ct lint \
            --all \
            --chart-dirs helm/charts \
            --validate-maintainers=false
