# based on: https://github.com/helm/charts-repo-actions-demo/blob/main/.github/workflows/lint-test.yaml
name: test

on:
  push:
    branches:
      - main
    paths:
      - "helm/charts/**"
      - "!helm/charts/index.yaml"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "helm/charts/**"
      - "!helm/charts/index.yaml"
      - ".github/workflows/test.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "v1.23.6"
          - "v1.22.9"
          - "v1.21.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Create k8s cluster
        uses: helm/kind-action@v1.3.0
        with:
          node_image: "kindest/node:${{ matrix.k8s }}"
          kubectl_version: "${{ matrix.k8s }}"

      - name: Get cluster info/nodes
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: create kubeedge-ca
        run: |
          #!/bin/bash
          set -e
          mkdir certs
          cd certs
          curl -JLO "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
          chmod +x mkcert-v*-linux-amd64
          CAROOT=$(pwd) ./mkcert-v1.4.4-linux-amd64 -client -cert-file server.crt  -key-file server.key "*.nip.io" "*.kubeedge.svc.cluster.local" 
          kubectl create namespace kubeedge 
          kubectl -n kubeedge create secret tls kubeedge-ca --cert=rootCA.pem --key=rootCA-key.pem
          kubectl -n kubeedge create secret generic kubeedge-certs --from-file=server.crt --from-file=server.key

      - name: Run chart-testing on kubeedge helm chart (install)
        run: |-
          ct install \
            --charts helm/charts/kubeedge \
            --namespace kubeedge

      - name: Get cluster info/nodes
        run: |
          kubectl get -n kubeedge pods -o wide
          kubectl get -n kubeedge services
